# Convert CSV to sqlite

In [1]:
import pandas as pd
pd.options.display.max_columns = None

df = pd.read_csv("powerplants.csv")
df.head(2)

,plant_code,plant_name,utility_name,utility_id,sector_name,city,county,zip,street_address,primary_source,total_mw,coal_mw,ng_mw,crude_mw,bio_mw,hydro_mw,hydro_mw.1,nuclear_mw,solar_mw,wind_mw,geo_mw,other_mw,source_des,tech_desc,source,period,latitude,longitude
0,2,Bankhead Dam,Alabama Power Co,195,Electric Utility,Northport,Tuscaloosa,35476,19001 Lock 17 Road,hydroelectric,56.0,0.0,0.0,0.0,NaN,56.0,0.0,0.0,0.0,0.0,NaN,NaN,Hydroelectric = 56 MW,Conventional Hydroelectric,"EIA-860, EIA-860M and EIA-923",201607,33.458665,-87.356823
1,3,Barry,Alabama Power Co,195,Electric Utility,Bucks,Mobile,36512,North Highway 43,coal,2160.5,1088.5,1072.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,"Coal = 1088.5 MW, Natural Gas = 1072 MW",Conventional Steam Coal; Natural Gas Fired Com...,"EIA-860, EIA-860M and EIA-923",201607,31.006900,-88.010300

In [2]:
df.dtypes

plant_code          int64
plant_name         object
utility_name       object
utility_id          int64
sector_name        object
city               object
county             object
zip                 int64
street_address     object
primary_source     object
total_mw          float64
coal_mw           float64
ng_mw             float64
crude_mw          float64
bio_mw            float64
hydro_mw          float64
hydro_mw.1        float64
nuclear_mw        float64
solar_mw          float64
wind_mw           float64
geo_mw            float64
other_mw          float64
source_des         object
tech_desc          object
source             object
period              int64
latitude          float64
longitude         float64
dtype: object

In [4]:
import sqlite3
import os

# Create energy.sqlite3 database
conn = sqlite3.connect('energy.sqlite3')

# Write the data to a sqlite table
df.to_sql('powerplants', conn, if_exists='replace', index=False)

conn.close()